# Generated by Django 4.2.5 on 2023-10-01 14:59

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerId", models.AutoField(primary_key=True, serialize=False)),
                ("CustFirstName", models.CharField(max_length=128)),
                ("CustLastName", models.CharField(max_length=128)),
                ("CustCellNo", models.CharField(max_length=20)),
                ("CustEmail", models.EmailField(max_length=254, unique=True)),
                ("CustPassword", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="EnquiryCat",
            fields=[
                ("EnqCatId", models.AutoField(primary_key=True, serialize=False)),
                ("EnqCatName", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="ProdCategory",
            fields=[
                ("ProdCatId", models.AutoField(primary_key=True, serialize=False)),
                ("ProdCatName", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("ProductId", models.AutoField(primary_key=True, serialize=False)),
                ("ProdName", models.CharField(max_length=100, unique=True)),
                ("ProdDescr", models.CharField(max_length=128, unique=True)),
                ("ProdQtyAvail", models.IntegerField()),
                ("ProdPrice", models.IntegerField()),
                (
                    "ProdCatId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.prodcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("OrderId", models.AutoField(primary_key=True, serialize=False)),
                ("Qty", models.IntegerField()),
                ("OrderTotal", models.IntegerField()),
                ("OrderDeliveryAddress", models.CharField(max_length=128)),
                (
                    "OrderDate",
                    models.DateTimeField(
                        default=mysite.models.Order.get_default_datetime, max_length=20
                    ),
                ),
                (
                    "CustomerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.customer",
                    ),
                ),
                (
                    "ProductId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginDetails",
            fields=[
                ("LoginId", models.AutoField(primary_key=True, serialize=False)),
                ("LoginEmail", models.EmailField(max_length=254)),
                ("LoginPassword", models.CharField(max_length=20)),
                (
                    "LoginDateTime",
                    models.DateTimeField(
                        default=mysite.models.LoginDetails.get_default_datetime
                    ),
                ),
                (
                    "CustomerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustEnq",
            fields=[
                ("EnqId", models.AutoField(primary_key=True, serialize=False)),
                ("EnqComment", models.CharField(max_length=128)),
                (
                    "EnqDate",
                    models.DateTimeField(
                        default=mysite.models.CustEnq.get_default_datetime,
                        max_length=20,
                    ),
                ),
                (
                    "CustomerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.customer",
                    ),
                ),
                (
                    "EnqCatId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.enquirycat",
                    ),
                ),
            ],
        ),
    ]
